Project/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'
urlpatterns = [
    path('index', views.index, name='index'),
    path('listadoSQL', views.listadoSQL, name='listadoSQL'),

    path('Menu', views.Menu, name='Menu'),
    path('VistaArtistas', views.VistaArtistas, name='VistaArtistas'),
    path('REGISTER', views.Register, name='REGISTER'),
    path('VistaMercado', views.VistaMercado, name='VistaMercado'),
    path('artes', views.Artes, name='artes'), 
    path('VistaCarrusel', views.VistaCarrusel, name='VistaCarrusel'),
    path('LOGIN', views.Login, name='LOGIN'),
    path('ARTICULO', views.Articulo, name='ARTICULO'),
    path('CARRITO', views.Carrito, name='CARRITO'),

    path('crud', views.crud, name='crud'),
    path('usuariosAdd', views.usuariosAdd, name='usuariosAdd'),
    path('usuarios_del/<str:pk>', views.usuarios_del, name='usuarios_del'),
    path('usuarios_findEdit/<str:pk>', views.usuarios_findEdit, name='usuarios_findEdit'),
    path('usuariosUpdate', views.usuariosUpdate, name='usuariosUpdate'),
]

Project/usuarios/models.py
from django.db import models

class Usuario(models.Model):
    rut = models.CharField(primary_key=True, max_length=10)
    nombre = models.CharField(max_length=20)
    email = models.EmailField(unique=True, max_length=100, blank=True, null=True)
    activo = models.IntegerField()
def __str__(self):
    return str(self.nombre)

Project/usuarios/forms.py
from django import forms
from .models import Genero

from django.forms import ModelForm

class GeneroForm(ModelForm):
    class Meta:
        model = Genero
        fields = ["genero",]
        labels = {'genero': 'Género',}

Project/usuarios/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Usuario
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    usuarios=Usuario.objects.all()
    context={"usuarios":usuarios}
    return render(request, 'usuarios/index.html', context)

def listadoSQL(request):
    usuarios= Usuario.objects.raw('SELECT * FROM usuarios_usuario')
    print(usuarios)
    context={"usuarios":usuarios}
    return render(request, 'usuarios/listadoSQL.html', context)


def Menu(request):
    return render(request, 'usuarios/Menu.html')

def VistaArtistas(request):
    return render(request, 'usuarios/VistaArtistas.html')

def Register(request):
    return render(request, 'usuarios/REGISTER.html')

def VistaMercado(request):
    return render(request, 'usuarios/VistaMercado.html')

def Artes(request):
    return render(request, 'usuarios/artes.html')

def VistaCarrusel(request):
    return render(request, 'usuarios/VistaCarrusel.html')

def Login(request):
    return render(request, 'usuarios/LOGIN.html')

def Articulo(request):
    return render(request, 'usuarios/ARTICULO.html')

def Carrito(request):
    return render(request, 'usuarios/CARRITO.html')


@login_required
def crud(request):
    request.session["usuario"] = "dserey"
    usuarios = Usuario.objects.all()
    context = {'usuarios': usuarios}
    return render(request, 'usuarios/usuarios_list.html', context)

@login_required
def usuariosAdd(request):
    request.session["usuario"] = "dserey"
    if request.method != "POST":
        return render(request, 'usuarios/usuarios_add.html')
    else:
        rut=request.POST["rut"]
        nombre=request.POST["nombre"]
        email=request.POST["email"]
        activo="1"

        obj=Usuario.objects.create(
            rut=rut,
            nombre=nombre,
            email=email,
            activo=1
        )
    obj.save()
    context={'mensaje':"Ok, datos grabados..."}
    return render(request, 'usuarios/usuarios_add.html', context)

@login_required
def usuarios_del(request,pk):
    request.session["usuario"] = "dserey"
    context={}
    try:
        usuario = Usuario.objects.get(rut=pk)

        usuario.delete()
        mensaje = "Bien, datos eliminados..."
        usuarios = Usuario.objects.all()
        context = {'usuarios': usuarios, 'mensaje': mensaje}
        return render(request, 'usuarios/usuarios_list.html', context)
    except:
        mensaje = "Error, rut no existe..."
        usuarios = Usuario.objects.all()
        context = {'usuarios': usuarios, 'mensaje': mensaje}
        return render(request, 'usuarios/usuarios_list.html', context)

@login_required
def usuarios_findEdit(request, pk):
    request.session["usuario"] = "dserey"
    if pk != "":
        usuario=Usuario.objects.get(rut=pk)

        context = {'usuario':usuario}
        if usuario:
            return render(request, 'usuarios/usuarios_edit.html', context)
        else:
            context = {'mensaje':"Error, rut no existe..."}
            return render(request, 'usuarios/usuarios_list.html', context)

@login_required
def usuariosUpdate(request):
    request.session["usuario"] = "dserey"
    if request.method == "POST":
        rut=request.POST["rut"]
        nombre=request.POST["nombre"]
        email=request.POST["email"]
        activo="1"
        usuario = Usuario()
        usuario.rut=rut
        usuario.nombre=nombre
        
        usuario.email=email
        usuario.activo=1
        usuario.save()
        context = {'mensaje': "Ok, datos actualizados...", 'usuario': usuario}
        return render(request, 'usuarios/usuarios_edit.html', context)
    else:
        usuarios = Usuario.objects.all()
        context = {'usuarios': usuarios}
        return render(request, 'usuarios/usuarios_list.html', context)

Project/usuarios/templates/usuarios/REGISTER.html
{% extends 'usuarios/base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/style.css'}%">
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    {% block content %}
    <body background="{% static 'img/unnamed.jpg'%}">
        <form action="{% url 'usuarios:Menu' %}" method="" id='formulario'>
            <div class="container-sm">
                <h1 style="text-align: center;">Register</h1>
                <div class="mb-3">
                    <label for="exampleInputUser1" class="form-label">Nombre de usuario</label>
                    <input type="user" class="form-control" id="user" aria-describedby="userHelp" placeholder="Ingresa tu Nombre de usuario">
                    <div id="userHelp" class="form-text"></div>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Direccíon de correo</label>
                    <input type="email" class="form-control" id="correo" aria-describedby="emailHelp" placeholder="Ingresa tu Direccíon de correo">
                    <div id="emailHelp" class="form-text"></div>
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                    <input type="password" class="form-control" id="password" placeholder="Ingresa tu Contraseña">
                </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
            <p id='error' class="error"></p>
            </div>
        </form>
        <script src="{% static 'scripts/VALIDACION.js' %}"></script>         
    </body>
    {% endblock %}
</html>

Project/usuarios/templates/usuarios/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Cargando CSS -->
        <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
        <!-- Cargando Bootstrap CSS y JS (de bootstrap) -->
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
        <div id="containerNav">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'usuarios:Menu' %}">
                        <img src="{% static 'img/Logo.webp' %}" alt="GroundZero" width="40" height="35">
                    </a>
                    <a class="navbar-brand" href="{% url 'usuarios:Menu' %}">Ground Zero</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'usuarios:Menu' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Crear cuenta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuarios:VistaArtistas' %}">Artistas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuarios:VistaMercado' %}">Mercado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuarios:artes' %}">Obras</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Articulos
                            </a>
                            <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'usuarios:VistaCarrusel' %}">Pinceles</a></li>
                            <li><a class="dropdown-item" href="{% url 'usuarios:VistaCarrusel' %}">Pinturas</a></li>
                            <li><a class="dropdown-item" href="{% url 'usuarios:VistaCarrusel' %}">Atriles</a></li>
                            <li><a class="dropdown-item" href="{% url 'usuarios:VistaCarrusel' %}">Telas</a></li>
                            </ul>
                        </li>
                        <form class="d-flex" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Buscar</button>
                        </form>
                        {% if user.is_authenticated %}
                            <div class="d-flex">
                                <a class="btn btn-primary" href="{% url 'administrador:crudMenu' %}" role="button">Admin</a>  
                            </div>
                        {% endif %}
                    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">Perfil</a>
                            <ul class="dropdown-menu">
                                {% if user.is_authenticated %}
                                    {{user.username}}
                                    <li><a href="{% url 'logout' %}">Cerrar sessión</a></li> 
                                {% else %}
                                    <a href = "{% url 'login' %}">Iniciar Sesión</a>
                                {% endif %}
                            </ul>
                        <div id="perfil-icon" style="display: none;">
                            <i class="fas fa-user-circle"></i>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        {% block content %}

        {% endblock %}
    </body>
</html>

Project/usuarios/templates/usuarios/generos_add.html
{% extends 'administrador/base2.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
    </head>
    {% block content %}
    <body>
        <h2>FORMULARIO GÉNEROS</h2><br><br>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_table }}                
            <input type="submit" value="Agregar">                
        </form> 
        <br>

        <a href="{% url 'usuarios:crud_generos' %}"> Volver </a>
        <br>
        <div id="idMensajes">
            {% if mensajes %}
            {{mensaje}}
            {% endif %}
        </div>
    </body>
    {% endblock %}
</html>

Project/usuarios/templates/usuarios/generos_edit.html
{% extends 'administrador/base2.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
    </head>
    {% block content %}
    <body>

        <div style=" text-align: center;">
            
            {% if genero %}
            <h2>FORMULARIO CRUD PARA GÉNEROS</h2><br>
                <form action="{% url 'usuarios:usuariosUpdate' %}" method="POST">
                    {% csrf_token %}

                    {{form.as_table}}
                    
                    <input type="submit" name="opcion" value="Actualizar">
            </form> <br><br>
            {% endif %}
            <div id="idMensajes">
                {% if mensajes %}
                {{mensaje}}
                {% endif %}
            </div>
            <br><br>
            <a href="{% url 'usuarios:crud_generos' %}"> Volver </a>
        </div>
    </body>
    {% endblock %}
</html>

Project/usuarios/templates/usuarios/generos_list.html
{% extends 'administrador/base2.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
    </head>
    {% block content %}
    <body>


        <h1>EDITAR DATOS DE GENEROS</h1>
        <br>

        <button type="button">
            <a href="{% url 'usuarios:generosAdd' %}"> Agregar</a>
        </button>

        <div id="idMensajes">
            {% if mensaje %}
                {{mensaje}}
            {% endif %}
        </div>

        <table>
            {% if generos %}
                <th>Género</th>
                <th>Eliminar</th>
                <th>Modificar</th>              
                {% for x in generos %}
                    <tr>
                        <td> {{ x.genero }}
                        <td> <a href="{% url 'usuarios:generos_del' pk=x.id_genero %}">Eliminar</a>
                        <td> <a href="{% url 'usuarios:generos_edit' pk=x.id_genero %}">Modificar</a>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>

        <button type="button">
            <a href="{% url 'administrador:crudMenu' %}">Volver</a>
        </button>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            $(document).ready(function(){
                $("#idMensajes").delay(2000).fadeOut("slow");
            });
        </script>
    </body>
    {% endblock %}
</html>

Project/usuarios/templates/usuarios/usuarios_add.html
{% extends 'administrador/base2.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
    </head>
    {% block content %}
    <body>

        <div style=" text-align: center;">
            
            <h2>FORMULARIO CRUD PARA USUARIOS</h2>
            <form action="{% url 'usuarios:usuariosAdd' %}"   method="POST">
                {% csrf_token %}
                <pre>Rut:               <input type="text" name="rut"     required></pre>
                <pre>Nombre:            <input type="text" name="nombre"  required></pre>
                <pre>Email:     <input type="mail" name="email" required></pre>
                <input type="submit" name="opcion" value="Agregar">
            </form> <br><br>
            <a href="{% url 'usuarios:crud' %}"> Volver </a>
            <br>
            <div id="idMensajes">
                {% if mensajes %}
                {{mensaje}}
                {% endif %}
            </div>
        </div>
    </body>
    {% endblock %}
</html>

Project/usuarios/templates/usuarios/usuarios_edit.html
{% extends 'administrador/base2.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
    </head>
    {% block content %}
    <body>

        <div style=" text-align: center;">
            
            {% if usuario %}
            <h2>FORMULARIO CRUD PARA USUARIOS</h2>
            <form action="{% url 'usuarios:usuariosUpdate' %}" method="POST">
                {% csrf_token %}

                <pre>Rut:               <input type="text" name="rut"       value="{{usuario.rut}}"></pre>
                <pre>Nombre:            <input type="text" name="nombre"    value="{{usuario.nombre}}"></pre>
                <pre>Email:     <input type="mail" name="email" value="{{usuario.email}}"></pre>
                <input type="submit" name="opcion" value="Actualizar">
                
            </form> <br><br>
            {% endif %}
            <div id="idMensajes">
                {% if mensajes %}
                {{mensaje}}
                {% endif %}
            </div>
            <br><br>
            <a href="{% url 'usuarios:crud' %}"> Volver </a>
        </div>
    </body>
    {% endblock %}
</html>

Project/usuarios/templates/usuarios/usuarios_list.html
{% extends 'administrador/base2.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
    </head>
    {% block content %}
    <body>


        <h1>EDITAR DATOS DE USUARIOS</h1>
        <br>

        <button type="button">
            <a href="{% url 'usuarios:usuariosAdd' %}"> Agregar</a>
        </button>
    

        <div id="idMensajes">
            {% if mensaje %}
                {{mensaje}}
            {% endif %}
        </div>

        <table>
            {% if usuarios %}
                <th>Rut</th>
                <th>Nombre</th>
                <th>Eliminar</th>
                <th>Modificar</th>
                {% for x in usuarios %}
                    <tr>
                        <td> {{ x.rut }}
                        <td> {{ x.nombre }}
                        <td> <a href="{% url 'usuarios:usuarios_del' pk=x.rut %}">Eliminar</a>
                        <td> <a href="{% url 'usuarios:usuarios_findEdit' pk=x.rut %}">Modificar</a>    
                    </tr>
                {% endfor %}
            {% endif %}
        </table>

        <button type="button">
            <a href="{% url 'administrador:crudMenu' %}">Volver</a>
        </button>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            $(document).ready(function(){
                $("#idMensajes").delay(2000).fadeOut("slow");
            });
        </script>
    </body>
    {% endblock %}
</html>